global:
  namespace: kubefinops
  kafkaBootstrap: "infra-kafka:9092"
  mongoUri: "mongodb://infra-mongodb:27017/kubefinops"

recommender:
  image: kubefinops/recommender-service:latest
  port: 8081
  prometheusUrl: "http://infra-monitoring-prometheus:9090"
  minioUrl: "http://infra-minio:9000"

policy:
  image: kubefinops/policy-service:latest
  port: 8082

bot:
  image: kubefinops/gitops-bot:latest
  port: 8083
  gitRepoUrl: "http://gitea-http:3000/gitops/config.git"
