apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-bot
  labels:
    {{- include "kubefinops.labels" . | nindent 4 }}
    service: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bot
  template:
    metadata:
      labels:
        service: bot
    spec:
      containers:
      - name: bot
        image: {{ .Values.bot.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.bot.port }}
        env:
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: {{ .Values.global.kafkaBootstrap }}
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username='{{ .Values.global.kafkaUser }}' password='{{ .Values.global.kafkaPassword }}';"
        - name: GITOPS_REPO_URL
          value: {{ .Values.bot.gitRepoUrl }}
        - name: GITOPS_GIT_USER
          value: {{ .Values.bot.gitUser }}
        - name: GITOPS_GIT_TOKEN
          value: {{ .Values.bot.gitToken }}
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-bot
spec:
  selector:
    service: bot
  ports:
  - port: 8083
    targetPort: 8083
