apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-service
  labels:
    {{- include "kubefinops.labels" . | nindent 4 }}
    service: recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      service: recommender
  template:
    metadata:
      labels:
        service: recommender
    spec:
      containers:
      - name: recommender
        image: {{ .Values.recommender.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.recommender.port }}
        env:
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: {{ .Values.global.kafkaBootstrap }}
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_CONFIGURATION_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username='{{ .Values.global.kafkaUser }}' password='{{ .Values.global.kafkaPassword }}';"
        - name: SPRING_DATA_MONGODB_URI
          value: {{ .Values.global.mongoUri }}
        - name: PROMETHEUS_URL
          value: {{ .Values.recommender.prometheusUrl }}
        - name: MINIO_URL
          value: {{ .Values.recommender.minioUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    service: recommender
  ports:
  - port: 8081
    targetPort: 8081
